[package]
name = "dexos-android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { workspace = true }
kernel = { path = "../../../kernel" }
security = { path = "../../../crates/security" }
crypto = { path = "../../../crates/crypto" }
p2p = { path = "../../../crates/p2p" }